### ISSUE TITLE
Strategy Pattern

### ISSUE THREAD

**Issue by jifengnan** [echoTheLiar/JavaCodeAcc#2]
I don't think the demo code for the strategy pattern is correct.
The following code is a demo for the strategy pattern:
```
if(strategyName == "StrategyA"){
     new StrategyA().methodName();
}else if(strategyName == "StrategyB"){
     new StrategyB().methodName();
}(strategyName == "StrategyC"){
     new StrategyC().methodName();
}
```

Your code is more like a delegate pattern:
```
Class Dispatcher{
    private Map<String, Strategy> map = new HashMap<String, Strategy>();

    public void putStrategyMap(String name, Strategy strategy ){
        map.put(name, strategy);
    }

    public void do(String name){
        map.get(name).methodName();
    }
}

Class StrategyClient{
    public static void main(String[] args) {
	Dispatcher context = new Dispatcher();
        context.putStrategyMap("StrategyA", new StrategyA());
        context.putStrategyMap("StrategyB", new StrategyB());
        context.putStrategyMap("StrategyC", new StrategyC());

	context.do("StrategyA");
	context.do("StrategyB");
	context.do("StrategyC");
    }
}
```

**Comment by echoTheLiar** [comment]
Before answering your question, I wanna make sure that the codes you copied are from my repo, cause I can't find the target codes which are like

> Class Dispatcher{
    private Map<String, Strategy> map = new HashMap<String, Strategy>();

    public void putStrategyMap(String name, Strategy strategy ){
        map.put(name, strategy);
    }

    public void do(String name){
        map.get(name).methodName();
    }
}

Class StrategyClient{
    public static void main(String[] args) {
	Dispatcher context = new Dispatcher();
        context.putStrategyMap("StrategyA", new StrategyA());
        context.putStrategyMap("StrategyB", new StrategyB());
        context.putStrategyMap("StrategyC", new StrategyC());

	context.do("StrategyA");
	context.do("StrategyB");
	context.do("StrategyC");
    }
}


 in:
JavaCodeAcc/src/designpattern/strategy/Context.java  
JavaCodeAcc/src/designpattern/strategy/Strategy.java
JavaCodeAcc/src/designpattern/strategy/StrategyClient.java

**Comment by echoTheLiar** [comment]
Before answering your question, I wanna make sure that the codes you copied are from my repo, cause I can't find the target codes which are like
`Class Dispatcher{
    private Map<String, Strategy> map = new HashMap<String, Strategy>();

    public void putStrategyMap(String name, Strategy strategy ){
        map.put(name, strategy);
    }

    public void do(String name){
        map.get(name).methodName();
    }
}

Class StrategyClient{
    public static void main(String[] args) {
	Dispatcher context = new Dispatcher();
        context.putStrategyMap("StrategyA", new StrategyA());
        context.putStrategyMap("StrategyB", new StrategyB());
        context.putStrategyMap("StrategyC", new StrategyC());

	context.do("StrategyA");
	context.do("StrategyB");
	context.do("StrategyC");
    }
}
`
in:
JavaCodeAcc/src/designpattern/strategy/Context.java
JavaCodeAcc/src/designpattern/strategy/Strategy.java
JavaCodeAcc/src/designpattern/strategy/StrategyClient.java

**Comment by echoTheLiar** [comment]
Before answering your question, I wanna make sure that the codes you copied are from my repo, cause I can't find the target codes in:
JavaCodeAcc/src/designpattern/strategy/Context.java
JavaCodeAcc/src/designpattern/strategy/Strategy.java
JavaCodeAcc/src/designpattern/strategy/StrategyClient.java
Please paste where the codes are from, thanks.
